### ISSUE TITLE
安装后，按要求配置，报错Plugin apply failed: Cannot read property 'routes' of undefined

### ISSUE THREAD

**Issue by ghost** [umijs/umi-plugin-antd-icon-config#12]
![image](https://user-images.githubusercontent.com/47747920/79292128-f2e55780-7f02-11ea-9177-1aedfd79d6d2.png)
麻烦问一下，这是什么原因

**Comment by kzabc** [comment]
我也遇到；

**Comment by metafysik** [comment]
I have same issues.

**Comment by zlyyyy** [comment]
同问题。。

**Comment by linfengluo** [comment]
Plugin apply failed: Cannot read property 'routes' of undefined
×  error     TypeError: Cannot read property 'routes' of undefined
    at Array.<anonymous> (E:\zhicheng-mall-admin\node_modules\umi-plugin-antd-icon-config\lib/index.js:56:38)
    at register.opts (E:\zhicheng-mall-admin\node_modules\umi-build-dev\lib\PluginAPI.js:219:25)
    at reduce (E:\zhicheng-mall-admin\node_modules\umi-build-dev\lib\Service.js:308:16)
    at Array.reduce (<anonymous>)
    at Service.applyPlugins (E:\zhicheng-mall-admin\node_modules\umi-build-dev\lib\Service.js:304:42)
    at FilesGenerator.generateFiles (E:\zhicheng-mall-admin\node_modules\umi-build-dev\lib\FilesGenerator.js:235:18)
    at FilesGenerator.generate (E:\zhicheng-mall-admin\node_modules\umi-build-dev\lib\FilesGenerator.js:157:10)
    at service._applyPluginsAsync.then (E:\zhicheng-mall-admin\node_modules\umi-build-dev\lib\plugins\commands\dev\index.js:108:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bouti@2.7.4 start: `cross-env MOCK=none umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bouti@2.7.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Feng\AppData\Roaming\npm-cache\_logs\2020-06-12T06_57_44_561Z-debug.log

**Comment by haichaoshi** [comment]
"peerDependencies": {
    "umi": "3.x"
  },

may need to upgrade umi to 3.x

**Comment by anchor-sherry** [comment]
遇到这个问题 +1

**Comment by sunwenli** [comment]
package.json 里配置的 umi 3.x , 项目里使用的是 umi 2.8.7

**Comment by youxinyun** [comment]
遇到这个问题 +10

**Comment by sunwenli** [comment]
已经收到您的来信，我会尽快回复。
