### ISSUE TITLE
安装umi-plugin-antd-icon-config插件失败

### ISSUE THREAD

**Issue by zhoachenIt** [umijs/umi-plugin-antd-icon-config#14]
命令：yarn add umi-plugin-antd-icon-config -D
错误描述：
plugin umi-plugin-antd-icon-config is already registered by D:/Workspace/JavaWorkspace/other/AntDesignUI/node_modules/umi-plugin-antd-icon-config/lib/index.js, plugin from D:/Workspace/JavaWorkspace/other/AntDesignUI/node_modules/umi-plugin-antd-icon-config/lib/index.js register failed.
Error: plugin umi-plugin-antd-icon-config is already registered by D:/Workspace/JavaWorkspace/other/AntDesignUI/node_modules/umi-plugin-antd-icon-config/lib/index.js, plugin from D:/Workspace/JavaWorkspace/other/AntDesignUI/node_modules/umi-plugin-antd-icon-config/lib/index.js register failed.
    at Service.registerPlugin (D:\Workspace\JavaWorkspace\other\AntDesignUI\node_modules\@umijs\core\lib\Service\Service.js:420:13)
    at Service.initPlugin (D:\Workspace\JavaWorkspace\other\AntDesignUI\node_modules\@umijs\core\lib\Service\Service.js:404:10)
    at Service.initPresetsAndPlugins (D:\Workspace\JavaWorkspace\other\AntDesignUI\node_modules\@umijs\core\lib\Service\Service.js:313:12)
    at D:\Workspace\JavaWorkspace\other\AntDesignUI\node_modules\@umijs\core\lib\Service\Service.js:227:13
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\Workspace\JavaWorkspace\other\AntDesignUI\node_modules\@umijs\core\lib\Service\Service.js:106:103)
    at _next (D:\Workspace\JavaWorkspace\other\AntDesignUI\node_modules\@umijs\core\lib\Service\Service.js:108:194)
    at D:\Workspace\JavaWorkspace\other\AntDesignUI\node_modules\@umijs\core\lib\Service\Service.js:108:364
    at new Promise (<anonymous>)
    at D:\Workspace\JavaWorkspace\other\AntDesignUI\node_modules\@umijs\core\lib\Service\Service.js:108:97
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by zhangminggeek** [comment]
我安装的时候也报错了

Path must be a string.
TypeError: Path must be a string.
    at Function.resolveSync [as sync] (C:\Users\86151\Desktop\umi\node_modules\@umijs\utils\node_modules\resolve\lib\sync.js:53:15)
    at map.path (C:\Users\86151\Desktop\umi\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js:90:29)
    at Array.map (<anonymous>)
    at getPluginsOrPresets (C:\Users\86151\Desktop\umi\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js:89:99)
    at resolvePlugins (C:\Users\86151\Desktop\umi\node_modules\@umijs\core\lib\Service\utils\pluginUtils.js:183:19)
    at new Service (C:\Users\86151\Desktop\umi\node_modules\@umijs\core\lib\Service\Service.js:183:59)
    at new Service (C:\Users\86151\Desktop\umi\node_modules\umi\lib\ServiceWithBuiltIn.js:50:5)
    at C:\Users\86151\Desktop\umi\node_modules\umi\lib\cli.js:98:15
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (C:\Users\86151\Desktop\umi\node_modules\umi\lib\cli.js:53:103)
error Command failed with exit code 1.

**Comment by superbogy** [comment]
+1
